#!/bin/bash

calculate_offsets() {
    
    align_hex=$(objdump -p /usr/lib/systemd/boot/efi/linuxx64.efi.stub | awk '$1 == "SectionAlignment" {print $2}')
    align=$((16#$align_hex))

    
    osrel_offs_hex=$(objdump -h "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" | awk 'NF==7 {size=strtonum("0x"$3); offset=strtonum("0x"$4)} END {print size + offset}')
    osrel_offs=$((osrel_offs_hex + align - osrel_offs_hex % align))

    
    cmdline_offс=$((osrel_offс + $(stat -Lc%s "/usr/lib/os-release")))
    cmdline_offс=$((cmdline_offс + align - cmdline_offс % align))

    
    initrd_offс=$((cmdline_offс + $(stat -Lc%s "/boot/cmdline.txt")))
    initrd_offс=$((initrd_offс + align - initrd_offс % align))

    
    linux_offс=$((initrd_offс + $(stat -Lc%s "/boot/comb_initrd.img")))
    linux_offс=$((linux_offс + align - linux_offс % align))

    
    objcopy \
        --add-section .osrel="/usr/lib/os-release"      --change-section-vma .osrel=$(printf 0x%x $osrel_offс) \
        --add-section .cmdline="/boot/cmdline.txt"      --change-section-vma .cmdline=$(printf 0x%x $cmdline_offс) \
        --add-section .initrd="/boot/comb_initrd.img"   --change-section-vma .initrd=$(printf 0x%x $initrd_offс) \
        --add-section .linux="/boot/vmlinuz-linux"      --change-section-vma .linux=$(printf 0x%x $linux_offс) \
        "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "linux.efi"
}


cat /boot/intel-ucode.img /boot/booster-linux.img > /boot/comb_initrd.img


calculate_offsets


cp "$(pwd)/linux.efi" /boot/EFI/Linux/linux.efi
